name: Rust Build

on:
  push:
    branches: [ "project" ]
  pull_request:
    branches: [ "project" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Build project
        working-directory: cmdflow
        run: cargo build --verbose
        env:
          CARGO_TERM_COLOR: always
          CARGO_TERM_PROGRESS_WIDTH: 50
          CARGO_TERM_PROGRESS_UNICODE: true

      - name: Set Build Status Badge
        id: badge
        run: |
          STATUS="passing"
          if [ "${{ job.status }}" != "success" ]; then
            STATUS="failing"
          fi
          echo "BADGE_URL=https://img.shields.io/badge/build-$STATUS-brightgreen?style=for-the-badge" >> $GITHUB_ENV

      - name: Show Badge URL
        run: echo "Badge URL: $BADGE_URL"
