name: Build

on:
  push:
    branches: ["project"]
  pull_request:
    branches: ["project"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Build cmdflow
        working-directory: cmdflow
        run: cargo build --verbose

      - name: Run tests (optional)
        working-directory: cmdflow
        run: cargo test --verbose

      - name: Check cmdflow runs
        working-directory: cmdflow
        run: ./target/debug/cmdflow --version
